version: 0.2

phases:
  install:
    commands:
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 905418471145.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t playwright-aws-demo .
      - docker tag playwright-aws-demo:latest 905418471145.dkr.ecr.ap-south-1.amazonaws.com/playwright-aws-demo:latest

  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push 905418471145.dkr.ecr.ap-south-1.amazonaws.com/playwright-aws-demo:latest