name: Build & Push to ECR via AWS CodeBuild

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-with-codebuild:
    runs-on:
      - self-hosted
      - linux
      - codebuild
      - buildspec-override:true  # 👈 Ensures buildspec.yml runs

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      # Optional: Upload Playwright test results after ECR push
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
