name: Build & Push to ECR via AWS CodeBuild

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-with-codebuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      # Optional: Run tests (uncomment if needed)
      # - name: Install dependencies
      #   run: npm ci

      # - name: Run Playwright tests
      #   run: npx playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
